# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/CPP-Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/CPP-Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/CPP-Project/CMakeFiles /workspaces/CPP-Project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/CPP-Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fmt.dir/build.make CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named menu

# Build rule for target.
menu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 menu
.PHONY : menu

# fast build rule for target.
menu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menu.dir/build.make CMakeFiles/menu.dir/build
.PHONY : menu/fast

#=============================================================================
# Target rules for targets named week04

# Build rule for target.
week04: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 week04
.PHONY : week04

# fast build rule for target.
week04/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week04.dir/build.make CMakeFiles/week04.dir/build
.PHONY : week04/fast

#=============================================================================
# Target rules for targets named week05

# Build rule for target.
week05: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 week05
.PHONY : week05

# fast build rule for target.
week05/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week05.dir/build.make CMakeFiles/week05.dir/build
.PHONY : week05/fast

#=============================================================================
# Target rules for targets named week06

# Build rule for target.
week06: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 week06
.PHONY : week06

# fast build rule for target.
week06/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week06.dir/build.make CMakeFiles/week06.dir/build
.PHONY : week06/fast

#=============================================================================
# Target rules for targets named week08

# Build rule for target.
week08: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 week08
.PHONY : week08

# fast build rule for target.
week08/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week08.dir/build.make CMakeFiles/week08.dir/build
.PHONY : week08/fast

#=============================================================================
# Target rules for targets named week09

# Build rule for target.
week09: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 week09
.PHONY : week09

# fast build rule for target.
week09/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week09.dir/build.make CMakeFiles/week09.dir/build
.PHONY : week09/fast

#=============================================================================
# Target rules for targets named week10

# Build rule for target.
week10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 week10
.PHONY : week10

# fast build rule for target.
week10/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week10.dir/build.make CMakeFiles/week10.dir/build
.PHONY : week10/fast

#=============================================================================
# Target rules for targets named week11

# Build rule for target.
week11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 week11
.PHONY : week11

# fast build rule for target.
week11/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week11.dir/build.make CMakeFiles/week11.dir/build
.PHONY : week11/fast

src/format.o: src/format.cpp.o
.PHONY : src/format.o

# target to build an object file
src/format.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fmt.dir/build.make CMakeFiles/fmt.dir/src/format.cpp.o
.PHONY : src/format.cpp.o

src/format.i: src/format.cpp.i
.PHONY : src/format.i

# target to preprocess a source file
src/format.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fmt.dir/build.make CMakeFiles/fmt.dir/src/format.cpp.i
.PHONY : src/format.cpp.i

src/format.s: src/format.cpp.s
.PHONY : src/format.s

# target to generate assembly for a file
src/format.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fmt.dir/build.make CMakeFiles/fmt.dir/src/format.cpp.s
.PHONY : src/format.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menu.o: src/menu.cpp.o
.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menu.dir/build.make CMakeFiles/menu.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i
.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menu.dir/build.make CMakeFiles/menu.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s
.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/menu.dir/build.make CMakeFiles/menu.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/point.o: src/point.cpp.o
.PHONY : src/point.o

# target to build an object file
src/point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week09.dir/build.make CMakeFiles/week09.dir/src/point.cpp.o
.PHONY : src/point.cpp.o

src/point.i: src/point.cpp.i
.PHONY : src/point.i

# target to preprocess a source file
src/point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week09.dir/build.make CMakeFiles/week09.dir/src/point.cpp.i
.PHONY : src/point.cpp.i

src/point.s: src/point.cpp.s
.PHONY : src/point.s

# target to generate assembly for a file
src/point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week09.dir/build.make CMakeFiles/week09.dir/src/point.cpp.s
.PHONY : src/point.cpp.s

src/test.o: src/test.cpp.o
.PHONY : src/test.o

# target to build an object file
src/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.o
.PHONY : src/test.cpp.o

src/test.i: src/test.cpp.i
.PHONY : src/test.i

# target to preprocess a source file
src/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.i
.PHONY : src/test.cpp.i

src/test.s: src/test.cpp.s
.PHONY : src/test.s

# target to generate assembly for a file
src/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/test.cpp.s
.PHONY : src/test.cpp.s

src/week04.o: src/week04.cpp.o
.PHONY : src/week04.o

# target to build an object file
src/week04.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week04.dir/build.make CMakeFiles/week04.dir/src/week04.cpp.o
.PHONY : src/week04.cpp.o

src/week04.i: src/week04.cpp.i
.PHONY : src/week04.i

# target to preprocess a source file
src/week04.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week04.dir/build.make CMakeFiles/week04.dir/src/week04.cpp.i
.PHONY : src/week04.cpp.i

src/week04.s: src/week04.cpp.s
.PHONY : src/week04.s

# target to generate assembly for a file
src/week04.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week04.dir/build.make CMakeFiles/week04.dir/src/week04.cpp.s
.PHONY : src/week04.cpp.s

src/week05.o: src/week05.cpp.o
.PHONY : src/week05.o

# target to build an object file
src/week05.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week05.dir/build.make CMakeFiles/week05.dir/src/week05.cpp.o
.PHONY : src/week05.cpp.o

src/week05.i: src/week05.cpp.i
.PHONY : src/week05.i

# target to preprocess a source file
src/week05.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week05.dir/build.make CMakeFiles/week05.dir/src/week05.cpp.i
.PHONY : src/week05.cpp.i

src/week05.s: src/week05.cpp.s
.PHONY : src/week05.s

# target to generate assembly for a file
src/week05.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week05.dir/build.make CMakeFiles/week05.dir/src/week05.cpp.s
.PHONY : src/week05.cpp.s

src/week06.o: src/week06.cpp.o
.PHONY : src/week06.o

# target to build an object file
src/week06.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week06.dir/build.make CMakeFiles/week06.dir/src/week06.cpp.o
.PHONY : src/week06.cpp.o

src/week06.i: src/week06.cpp.i
.PHONY : src/week06.i

# target to preprocess a source file
src/week06.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week06.dir/build.make CMakeFiles/week06.dir/src/week06.cpp.i
.PHONY : src/week06.cpp.i

src/week06.s: src/week06.cpp.s
.PHONY : src/week06.s

# target to generate assembly for a file
src/week06.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week06.dir/build.make CMakeFiles/week06.dir/src/week06.cpp.s
.PHONY : src/week06.cpp.s

src/week08.o: src/week08.cpp.o
.PHONY : src/week08.o

# target to build an object file
src/week08.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week08.dir/build.make CMakeFiles/week08.dir/src/week08.cpp.o
.PHONY : src/week08.cpp.o

src/week08.i: src/week08.cpp.i
.PHONY : src/week08.i

# target to preprocess a source file
src/week08.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week08.dir/build.make CMakeFiles/week08.dir/src/week08.cpp.i
.PHONY : src/week08.cpp.i

src/week08.s: src/week08.cpp.s
.PHONY : src/week08.s

# target to generate assembly for a file
src/week08.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week08.dir/build.make CMakeFiles/week08.dir/src/week08.cpp.s
.PHONY : src/week08.cpp.s

src/week09.o: src/week09.cpp.o
.PHONY : src/week09.o

# target to build an object file
src/week09.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week09.dir/build.make CMakeFiles/week09.dir/src/week09.cpp.o
.PHONY : src/week09.cpp.o

src/week09.i: src/week09.cpp.i
.PHONY : src/week09.i

# target to preprocess a source file
src/week09.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week09.dir/build.make CMakeFiles/week09.dir/src/week09.cpp.i
.PHONY : src/week09.cpp.i

src/week09.s: src/week09.cpp.s
.PHONY : src/week09.s

# target to generate assembly for a file
src/week09.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week09.dir/build.make CMakeFiles/week09.dir/src/week09.cpp.s
.PHONY : src/week09.cpp.s

src/week10.o: src/week10.cpp.o
.PHONY : src/week10.o

# target to build an object file
src/week10.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week10.dir/build.make CMakeFiles/week10.dir/src/week10.cpp.o
.PHONY : src/week10.cpp.o

src/week10.i: src/week10.cpp.i
.PHONY : src/week10.i

# target to preprocess a source file
src/week10.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week10.dir/build.make CMakeFiles/week10.dir/src/week10.cpp.i
.PHONY : src/week10.cpp.i

src/week10.s: src/week10.cpp.s
.PHONY : src/week10.s

# target to generate assembly for a file
src/week10.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week10.dir/build.make CMakeFiles/week10.dir/src/week10.cpp.s
.PHONY : src/week10.cpp.s

src/week11.o: src/week11.cpp.o
.PHONY : src/week11.o

# target to build an object file
src/week11.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week11.dir/build.make CMakeFiles/week11.dir/src/week11.cpp.o
.PHONY : src/week11.cpp.o

src/week11.i: src/week11.cpp.i
.PHONY : src/week11.i

# target to preprocess a source file
src/week11.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week11.dir/build.make CMakeFiles/week11.dir/src/week11.cpp.i
.PHONY : src/week11.cpp.i

src/week11.s: src/week11.cpp.s
.PHONY : src/week11.s

# target to generate assembly for a file
src/week11.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/week11.dir/build.make CMakeFiles/week11.dir/src/week11.cpp.s
.PHONY : src/week11.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fmt"
	@echo "... main"
	@echo "... menu"
	@echo "... test"
	@echo "... week04"
	@echo "... week05"
	@echo "... week06"
	@echo "... week08"
	@echo "... week09"
	@echo "... week10"
	@echo "... week11"
	@echo "... src/format.o"
	@echo "... src/format.i"
	@echo "... src/format.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/point.o"
	@echo "... src/point.i"
	@echo "... src/point.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... src/week04.o"
	@echo "... src/week04.i"
	@echo "... src/week04.s"
	@echo "... src/week05.o"
	@echo "... src/week05.i"
	@echo "... src/week05.s"
	@echo "... src/week06.o"
	@echo "... src/week06.i"
	@echo "... src/week06.s"
	@echo "... src/week08.o"
	@echo "... src/week08.i"
	@echo "... src/week08.s"
	@echo "... src/week09.o"
	@echo "... src/week09.i"
	@echo "... src/week09.s"
	@echo "... src/week10.o"
	@echo "... src/week10.i"
	@echo "... src/week10.s"
	@echo "... src/week11.o"
	@echo "... src/week11.i"
	@echo "... src/week11.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

